language: generic

dist: trusty
sudo: required

env:
  global:
    - DEPENDENCY_DIR="${TRAVIS_BUILD_DIR}/dependencies"

cache:
  directories:
    - ${DEPENDENCY_DIR}


matrix:
    include:
    - env: CXX=g++-7 CC=gcc-7
      addons:
        apt:
          packages:
            - g++-7
          sources: &sources
            - ubuntu-toolchain-r-test


install:
  - mkdir -p "${DEPENDENCY_DIR}" && cd "${DEPENDENCY_DIR}"
  - |
      if [[ ! -d "$(ls -A ${DEPENDENCY_DIR}/cmake)" ]]; then
        CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.tar.gz"
        mkdir -p cmake && travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C cmake
      fi
      export PATH="${DEPENDENCY_DIR}/cmake/bin:${PATH}"
  - cd ${TRAVIS_BUILD_DIR}


script:
  - script/ci_build.sh

